"""empty message

Revision ID: 08f9bc1fd6bc
Revises: b1e9181a7833
Create Date: 2026-07-05 21:50:33.043233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f9bc1fd6bc'
down_revision = 'b1e9181a7833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword_table', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=255), server_default=sa.text("'waiting'::character varying"), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
