"""empty message

Revision ID: b1e9181a7833
Revises: 3123277e9978
Create Date: 2026-07-05 21:49:34.356437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e9181a7833'
down_revision = '3123277e9978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=255), server_default=sa.text("'waiting'::character varying"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword_table', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
