#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@Time   : 2026/5/12 15:40
@Author : yange19940310@gmail.com
@File   : default_config.py
"""
# 应用默认配置项
DEFAULT_CONFIG = {
    # wft配置
    "WTF_CSRF_ENABLED": "False",

    # SQLAlchemy数据库配置
    "SQLALCHEMY_DATABASE_URI": "",
    "SQLALCHEMY_POOL_SIZE": 30,
    "SQLALCHEMY_POOL_RECYCLE": 3600,
    "SQLALCHEMY_ECHO": "True",

    # Redis数据库配置
    "REDIS_HOST": "localhost",
    "REDIS_PORT": 6379,
    "REDIS_USERNAME": "",
    "REDIS_PASSWORD": "",
    "REDIS_DB": 0,
    "REDIS_USE_SSL": "False",

    # Celery默认配置
    "CELERY_BROKER_DB": 1,
    "CELERY_RESULT_BACKEND_DB": 1,
    "CELERY_TASK_IGNORE_RESULT": "False",
    "CELERY_RESULT_EXPIRES": 3600,
    "CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP": "True",

    # 认证安全配置
    "ACCESS_TOKEN_TTL_SECONDS": 1800,
    "REFRESH_TOKEN_TTL_SECONDS": 2592000,
    "AUTH_COOKIE_SECURE": "False",
    "AUTH_COOKIE_SAMESITE": "Lax",
    "FRONTEND_ORIGIN": "http://localhost:5173,http://127.0.0.1:5173",

    # MCP 安全出站策略
    "MCP_REQUIRE_HTTPS": "True",
    "MCP_ALLOW_PRIVATE_NETWORKS": "False",
    "MCP_OUTBOUND_ALLOWED_PORTS": "443",
    "MCP_OUTBOUND_HOST_ALLOWLIST": "",
    "MCP_MAX_RESPONSE_BYTES": 10485760,

    # MCP 限流与熔断
    "MCP_RATE_LIMIT_WINDOW_SECONDS": 60,
    "MCP_RATE_LIMIT_ACCOUNT": 120,
    "MCP_RATE_LIMIT_SERVER": 60,
    "MCP_RATE_LIMIT_TOOL": 30,
    "MCP_CIRCUIT_FAILURE_THRESHOLD": 5,
    "MCP_CIRCUIT_FAILURE_WINDOW_SECONDS": 120,
    "MCP_CIRCUIT_BASE_BACKOFF_SECONDS": 30,
    "MCP_CIRCUIT_MAX_BACKOFF_SECONDS": 600,
    "MCP_CIRCUIT_HALF_OPEN_TIMEOUT_SECONDS": 30,
    "MCP_RESILIENCE_FAIL_OPEN": "True",
}